version: "3.8"
services:
  api:
    build:
      context: ./backend
    ports:
      - "8080:8080" # Expose the API to the internet through port 8000
    depends_on:
      - db
    networks:
      - backend_network
    environment:
      - ConnectionStrings__BiometricsDb=Host=db;Port=5432;Database=biometricsdb;Username=biometricsuser;Password=yourpassword;
      - ASPNETCORE_ENVIRONMENT=Development
      - JWTSecret=your_256_bit_jwt_secret_here_must_be_at_least_256_bit_long

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: biometricsdb
      POSTGRES_USER: biometricsuser
      POSTGRES_PASSWORD: yourpassword
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend_network

  frontend:
    image: node:21-alpine
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    command: sh -c "npm install && npm run dev"
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge

volumes:
  pgdata:
