version: "3.8"
services:
  api:
    build:
      context: ./backend
    ports:
      - "8080:8080" # Expose the API to the internet through port 8000
    depends_on:
      - db
    networks:
      - backend_network
    environment:
      - ConnectionStrings__BiometricsDb=Host=db;Port=5432;Database=biometricsdb;Username=biometricsuser;Password=yourpassword;
      - ASPNETCORE_ENVIRONMENT=Development
      - JWTSecret=your_jwt_secret_here

  db:
    image: postgres
    environment:
      POSTGRES_DB: biometricsdb
      POSTGRES_USER: biometricsuser
      POSTGRES_PASSWORD: yourpassword
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge

volumes:
  pgdata:
