version: "3.8"
services:
  api:
    build:
      context: ./backend
    depends_on:
      - db
    networks:
      - backend_network
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=biometricsdb;Username=${DB_USER};Password=${DB_PASSWORD};
      - ASPNETCORE_ENVIRONMENT=Production
      - JWTSecret=${JWT_SECRET}

  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - ./frontend/dist:/frontend_dist
    networks:
      - backend_network
    depends_on:
      - api
      - db

  db:
    image: postgres
    environment:
      # Replace the actual values with placeholders
      POSTGRES_DB: biometricsdb
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge

volumes:
  pgdata:
  caddy_data:
  caddy_config:
  frontend_dist:
